export const TABLE_STATUS = {
  FREE: 'libre',
  OCCUPIED: 'ocupada',
  WAITING_PAYMENT: 'esperando_pago'
};

export const PRODUCT_TYPE = {
  MENU: 'MENU',
  CARTA: 'CARTA'
};

export const CARTA_CATEGORY = {
  CAMARONES: 'CAMARONES',
  GALLINA: 'GALLINA',
  CARNES: 'CARNES',
  CUYES: 'CUYES',
  TRUCHAS: 'TRUCHAS',
  PESCADO: 'PESCADO',
  RONDA_CRIOLLA: 'RONDA_CRIOLLA',
  CAJA_CHINA: 'CAJA_CHINA',
  PATO: 'PATO',
  POLLOS: 'POLLOS',
  GASEOSAS: 'GASEOSAS',
  CERVEZAS: 'CERVEZAS',
  BEBIDAS: 'BEBIDAS',
  GUARNICIONES: 'GUARNICIONES',
  DESAYUNOS: 'DESAYUNOS',
  SANDWICH: 'SANDWICH',
  INFUSIONES: 'INFUSIONES',
  JUGOS: 'JUGOS',
  GALLETAS: 'GALLETAS',
  OTROS: 'OTROS'
};

export const PAYMENT_METHOD = {
  CASH: 'efectivo',
  CARD: 'tarjeta',
  QR: 'qr'
};

export const TABLE_COUNT = 15;

export const CARTA_CATEGORY_LABELS = {
  [CARTA_CATEGORY.CAMARONES]: 'Camarones',
  [CARTA_CATEGORY.GALLINA]: 'Gallina',
  [CARTA_CATEGORY.CARNES]: 'Carnes',
  [CARTA_CATEGORY.CUYES]: 'Cuyes',
  [CARTA_CATEGORY.TRUCHAS]: 'Truchas',
  [CARTA_CATEGORY.PESCADO]: 'Pescado',
  [CARTA_CATEGORY.RONDA_CRIOLLA]: 'Ronda Criolla',
  [CARTA_CATEGORY.CAJA_CHINA]: 'Caja China',
  [CARTA_CATEGORY.PATO]: 'Pato',
  [CARTA_CATEGORY.POLLOS]: 'Pollos',
  [CARTA_CATEGORY.GASEOSAS]: 'Gaseosas',
  [CARTA_CATEGORY.CERVEZAS]: 'Cervezas',
  [CARTA_CATEGORY.BEBIDAS]: 'Bebidas',
  [CARTA_CATEGORY.GUARNICIONES]: 'Guarniciones',
  [CARTA_CATEGORY.DESAYUNOS]: 'Desayunos',
  [CARTA_CATEGORY.SANDWICH]: 'Sándwich',
  [CARTA_CATEGORY.INFUSIONES]: 'Infusiones',
  [CARTA_CATEGORY.JUGOS]: 'Jugos',
  [CARTA_CATEGORY.GALLETAS]: 'Galletas',
  [CARTA_CATEGORY.OTROS]: 'Otros'
};

export const PAYMENT_METHOD_LABELS = {
  [PAYMENT_METHOD.CASH]: 'Efectivo',
  [PAYMENT_METHOD.CARD]: 'Tarjeta',
  [PAYMENT_METHOD.QR]: 'QR'
};
